/** @jsxImportSource @emotion/react */
import { css } from '@emotion/react'

import Track from '../../classes/Track.js';
import Head from 'next/head'
import Exhibit from '../../components/Exhibit/Exhibit.jsx';
import AudioTrackPlaylist from '../../components/AudioTrackPlaylist/AudioTrackPlaylist.jsx';
import styles from '../../styles/Home.module.css'

export default function Home() {
  let tracks = [
      {
          "title": "PRETENTIOUS",
          "explicit": true,
          "artists": [
              {
                  "name": "HAIDER SAMSARA",
                  "username": "haidersamsara",
                  "href": "/@haidersamsara"
              }
          ],
          "src": "https://sumire.s3.eu-west-2.amazonaws.com/audio/haidernism/track1.mp3",
          "id": "haidernism_track1"
      },
      {
          "title": "PRESSURE",
          "explicit": true,
          "artists": [
              {
                  "name": "HAIDER SAMSARA",
                  "username": "haidersamsara",
                  "href": "/@haidersamsara"
              }
          ],
          "src": "https://sumire.s3.eu-west-2.amazonaws.com/audio/haidernism/track2.mp3",
          "id": "haidernism_track2"
      },
      {
          "title": "THRU THE NITE",
          "explicit": true,
          "artists": [
              {
                  "name": "HAIDER SAMSARA",
                  "username": "haidersamsara",
                  "href": "/@haidersamsara"
              },
              {
                  "name": "Caracara",
                  "username": "caracara",
                  "href": "/@caracara"
              }
          ],
          "src": "https://sumire.s3.eu-west-2.amazonaws.com/audio/haidernism/track3.mp3",
          "id": "haidernism_track3"
      },
      {
          "title": "THOUGHT LOOPS",
          "explicit": true,
          "artists": [
              {
                  "name": "HAIDER SAMSARA",
                  "username": "haidersamsara",
                  "href": "/@haidersamsara"
              }
          ],
          "src": "https://sumire.s3.eu-west-2.amazonaws.com/audio/haidernism/track4.mp3",
          "id": "haidernism_track4"
      },
      {
          "title": "QUICKSAND",
          "explicit": true,
          "artists": [
              {
                  "name": "HAIDER SAMSARA",
                  "username": "haidersamsara",
                  "href": "/@haidersamsara"
              }
          ],
          "src": "https://sumire.s3.eu-west-2.amazonaws.com/audio/haidernism/track5.mp3",
          "id": "haidernism_track5"
      },
      {
          "title": "IN MY EYEZ",
          "explicit": true,
          "artists": [
              {
                  "name": "HAIDER SAMSARA",
                  "username": "haidersamsara",
                  "href": "/@haidersamsara"
              },
              {
                  "name": "Frank Lafunk"
              }
          ],
          "src": "https://sumire.s3.eu-west-2.amazonaws.com/audio/haidernism/track6.mp3",
          "id": "haidernism_track6"
      },
      {
          "title": "PAKI",
          "explicit": true,
          "artists": [
              {
                  "name": "HAIDER SAMSARA",
                  "username": "haidersamsara",
                  "href": "/@haidersamsara"
              }
          ],
          "src": "https://sumire.s3.eu-west-2.amazonaws.com/audio/haidernism/track7.mp3",
          "id": "haidernism_track7"
      },
      {
          "title": "PENITENT",
          "artists": [
              {
                  "name": "HAIDER SAMSARA",
                  "username": "haidersamsara",
                  "href": "/@haidersamsara"
              },
              {
                  "name": "Sylvia the House",
                  "username": "sylviathehouse",
                  "href": "/@sylviathehouse"
              }
          ],
          "explicit": true,
          "src": "https://sumire.s3.eu-west-2.amazonaws.com/audio/haidernism/track8.mp3",
          "id": "haidernism_track8"
      },
      {
          "title": "PHENOMENAL",
          "artists": [
              {
                  "name": "HAIDER SAMSARA",
                  "username": "haidersamsara",
                  "href": "/haidersamsara"
              }
          ],
          "explicit": false,
          "src": "https://sumire.s3.eu-west-2.amazonaws.com/audio/haidernism/track9.mp3",
          "id": "haidernism_track9"
      }
  ].map(
    /* construct Track objects from these JSON objects */
    track => Track.from(track)
  );

  return (
    <div className={styles.container}>
      <Head>
        <title>HAIDERNISM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> {/* TODO change this */}
      </Head>

      <Exhibit>
          <p>this is The Exhibition</p>
          <AudioTrackPlaylist tracks={tracks} />
          <img style={{height: '100%', width: '300%'}} src="https://via.placeholder.com/3840x2160/09f/fff" />
      </Exhibit>

    </div>
  )
}
