/** @jsxImportSource @emotion/react */
import { css } from '@emotion/react'

import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import TopBar from '../components/TopBar/TopBar.jsx';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>HAIDER SAMSARA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> {/* TODO change this */}
      </Head>

      <main className={styles.main}>
        <p>im aout to start wiling</p>
      </main>
    </div>
  )
}
