/** @jsxImportSource @emotion/react */
import { css } from '@emotion/react'

import Head from 'next/head'
import Exhibit from '../components/Exhibit/Exhibit.jsx';
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>HAIDERNISM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> {/* TODO change this */}
      </Head>

      <Exhibit>
          <p>this is The Exhibition</p>
          <img style={{height: '100%', width: '300%'}} src="https://via.placeholder.com/3840x2160/09f/fff" />
      </Exhibit>

    </div>
  )
}
