/** @jsxImportSource @emotion/react */
import { css } from '@emotion/react'
import styles from './index.module.css';
import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import Members from '../components/Members/Members.jsx';
import Carousel from '../components/Carousel/Carousel.jsx';
import BackgroundAnimation from '../components/BackgroundAnimation/BackgroundAnimation.jsx';
import ExhibitCard from '../components/ExhibitCard/ExhibitCard.jsx';
import DataContext from '../contexts/DataContext.jsx';
import { useContext } from 'react'

const Home = ()=>{
  const {members, exhibits} = useContext(DataContext);
  return (
    <>
      <Head>
        <title>made by sumire</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> {/* TODO change this */}
      </Head>

      <BackgroundAnimation />

      <main className={styles.main}>
        <Carousel>
          {exhibits.map(exhibit => {
            return <ExhibitCard exhibit={exhibit} />
          })
          }
        </Carousel>
      </main>

      <footer className={styles.footer}>
        <Members members={members} />
      </footer>
    </>
  )
}

Home.layout = 'CarouselLayout';

export default Home;
